ci: add publish report

diff --git a/.github/workflows/github.yml b/.github/workflows/github.yml
--- a/.github/workflows/github.yml
+++ b/.github/workflows/github.yml
@@ -41,3 +41,8 @@ jobs:
         run: chmod +x gradlew
       - name: Unit test with Gradle
         run: ./gradlew test jacocoTestReport
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
